export const Strings = {
  //auth
  phoneNumber: "Phone number",
  email: "Email",
  password: "Password",
  enterOTP: "Enter OTP Received by SMS",
  appName: "LOE",
  appFullName: "Last One Earth",
  userName: "User Name",
  next: "Next",
  capitalNext: "NEXT",
  follow: "+ Follow",
  message: "Message",
  back: "Back",
  introTitle1: "Help Keep the Planet Green",
  introTitle2: "Follow Specialized Communities",
  introTitle3: "Participate in Related Events",
  getStart: "Get Start",
  skip: "Skip",
  loremInpsum:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et lobortis purus, nec ultricies nisl. Donec fermentum tortor ut venenatis viverra. Mauris faucibus",
  signUpTitle: "Sign up",
  signInTitle: "Sign in",
  signUp: "SIGN UP",
  sendCode: "Send Code",
  signUpAgree: "By signing up, you agree to our",
  terms: "terms & conditions ",
  privacy: "privacy policy.",
  privacyPolicy: "Privacy Policy",
  haveAccount: "Already have an account?",
  dontHaveAccount: "Dont have an account? ",
  signIn: "SIGN IN",
  login: "LOGIN",
  forgetPass: "Forgot Password?",
  useSocial: "Or Use",
  singupWithPhoneNumber: "Sign up with phone number",
  singinWithPhoneNumber: "Sign in with phone number",
  signupWithEmail: "Sign up with email",
  signinWithEmail: "Sign in with email",
  signupLowerCase: "sign up",
  signInLowerCase: "sign in",
  publish: "Publish",
  YourStripeAccountInfo: "Your Stripe Account Info",
  CreateStripeAccount: "Create Stripe Account",
  PleaseCreateAStripeAccountToReceiveMoneyThenEnterItsInformationHere:
    "Please create a Stripe account to receive money. Then enter its information here.",
  PublishableKey: "Publishable Key",
  SecretKey: "Secret Key",
  //Logout
  yes: "Yes",
  no: "No",
  wantToLogout: "Are you sure you want to logout?",

  //Menu item
  logOut: "Log Out",

  //Forget password
  resetPass: "Reset Password",
  sendLink: "Send Reset Link",

  //Home
  all: "All",
  categories: "Categories",
  seeMore: "See More",
  posts: "Posts",
  comments: "Comments",
  likes: "Likes",
  sendComment: "Send Comment",
  seeAll: "See All",
  reserve: "Reserve",
  reserves: "Reserves",
  priceFree: "Price: Free",
  status: "Status",
  active: "Active",
  deactive: "Deactive",
  online: "Online",
  inPerson: "InPerson",
  price: "Price",
  detailName: "Detail Name",
  detailValue: "Detail Value",

  sold: "Sold",
  openMap: "Open Map",
  buyTicket: "Buy Ticket",
  donate: "Donate",
  SignforThisPetition: "Signed This Petition",
  signPetition: "Sign Petition",
  calenderView: "Calender View",
  eventsOn: "Events on",
  openLink: "Open Link",
  users: "Users",
  results: "Results",
  addNew: "Add New",
  //Detail
  details: "Details",
  send2: "Send",
  done: "Done",
  totalRequest: "Total Request",
  seeReserves: "See Reserves",
  openLocation: "Open Location",
  seeDonations: "See Donations",
  soldTickets: "Sold Tickets",
  seeDetail: "See Details",
  sign: "Sign",
  signPetitionTitle: "Your Personal information on the signature",
  name: "Name",
  email: "Email",
  signRealInformation: "Sign with real information",
  successfulSign: "Successful Sign",
  replyTo: "Reply to",
  share: "Share",
  reports: "Reports",
  deletePost: "Delete Post",
  deleteEvent: "Delete Event",
  deleteBlog: "Delete Blog",
  deleteAds: "Delete Ad",
  deleteEcoSpot: "Delete EcoSpot",
  report: "Report",
  selectAction: "Select Action",
  maxCapacity: "max capacity",
  createdDonationDetail: "Created Donation Details",
  createdTicketDeatils: "Created Ticket Details",
  requestedAmount: "Requested Amount",
  totalAmount: "Total Amount",
  contributors: "Contributors",
  allTickets: "All Tickets",
  pricePerTicket: "Price Per Ticket",
  categoryName: "Category Name",

  //Menu
  Settings: "Settings",
  FinancialPayment: "Financial & Payment",
  LikedPosts: "Liked Posts",
  JoinedEvents: "Joined Events",
  AboutSupport: "About & Support",
  InviteFriends: "Invite Friends",
  LogOut: "Log Out",
  Shop: "Shop",
  Ads: "Ads",
  SelectContentType: "Select Content Type",
  youAccountDetail: "Your Account Details",
  proExpiredDate: "Professional account until ",
  paid: "Paid",
  at: "at",
  userRequests: "User Requests",
  //Types
  post: "Post",
  events: "Events",
  ecoSpots: "Eco Spots",
  blog: "Blogs",
  places: "Places",
  blogTitle: "Blog",
  //Messages
  emptyString: "There is no result to show!",
  newMessage: "New Message",
  newGroup: "New Group",
  groups: "Groups",
  groupMembers: "Group Members",
  //Shop
  buy: "BUY",
  selectQuantity: "Select the Quantity",
  inventory: "Inventory",
  deliveryInfo: "Delivery Info",
  confirmInformation: "Confirm Your Delivery Information",
  fullName: "Full Name",
  requestBill: "Request Bill",
  note: "Note",
  shippingCost: "Shipping Cost",
  cart: "Cart",
  awaitingPayment: "Awaiting Payment",
  requestedBill: "Requested Bill",
  viewShop: "View Shop",
  paymentInfo: "Payment Info",
  paidSuccessful: "Paid Successful",
  deliverInfo: "Delivery Info",
  estimateDays: "Estimated days",
  remainedDays: "Remained days",
  customerConfirmedDeliver: "Customer Confirmed Delivery",
  billInfo: "Bill Info",
  yourBill: "Your Bill",
  sendDate: "Send Date",
  productPrice: "Product Price",
  quantity: "Quantity",
  vat: "VAT",
  total: "Total",
  payProductBill: "Pay Product Bill",
  selectThePaymentMethod: "Select The Payment Method",
  creditCard: "Credit Card",
  balance: "Balance",
  donationBalance: "Donation Balance",
  soldTicketBalance: "Sold Ticket Balance",
  shopBalance: "Shop Balance",
  ProFeaturesBalance: "Pro Features Balance",
  TotalShopBalance: "Total Shop Balance",
  WithdrawableShopBalance: "Withdrawable Shop Balance",
  SoldTicketsBalance: "Sold Tickets Balance",
  DonationsBalance: "Donations Balance",
  Withdraw: "Withdraws",
  withdraw: "Withdraw",
  WithdrawRequests: "Withdraw Requests",

  StripeDetails: "Stripe Details",
  ProSubscription: "Pro Subscription",
  yourBalance: "Your Balance",
  viewShop: "View Shop",
  productName: "Product Name",
  VAT: "VAT",
  myShop: "My Shop",
  youCanManageYourShopCatalogue: "You can manage your shop catalogue",
  orders: "Orders",
  youCanManageYourShopProducts: "You Can Manage Your Products",
  youHave: "You have",
  newOrders: "new orders",
  shopCategories: "Shop Categories",
  addNewCategory: "Add New Category",
  addNewProduct: "Add New Product",
  productDetails: "Product Details",
  deliverableRegion: "Deliverable Region",
  selectTheDeliverableRegions: "Select the deliverable regions",
  productMedia: "Product Media",
  addNewDetail: "Add New Detail",
  youCanAddYourProductPropertiesHere:
    "You can add your product properties here",
  rejectOrder: "Reject Order",
  AreYouSureYouWantToRejectTheOrder:
    "Are you sure you want to Reject the Order?",
  //Profile
  editProfile: "Edit Profile",
  confirm: "Confirm",
  emptyIntrest: "You dont have intrest yet!",
  emptyOtherUserInterset: "User has no intrest yet!",
  orderDetails: "Order Details",
  products: "Products",
  pending: "Pending",
  shops: "Shops",
  nameYourNewCategory: "Name your new category",
  sendBill: "Send Bill",
  reject: "Reject",
  accept: "Accept",
  deleteUserTitle: "Delete User",
  deleteUserDescription: "Are you sure you want to delete the user?",
  suspendUserTitle: "Suspend User",
  suspendUserDescription: "Are you sure you want to suspend the user?",
  allShops: "All Shops",
  allUsers: "All Users",
  //upload
  openCamera: "Open Camera",
  importGallery: "Import from Gallery",
  cancel: "Cancel",
  following: "Following",

  //settings
  personalInfo: "Personal Info",
  subPersonalInfo: "Gender, Birthday & Address Details",
  account: "Account",
  subAccount: "Interests, Phone Number, Blocked Users, Delete Account",
  notifications: "Notifications",
  subNotifications: "All Notifications",
  proAccount: "Switch To Pro Account",
  proAccountPro: "Pro Account",
  subProAccount:
    "online shop, organize paid events, create donations, access to privileged events and post advertisement",
  language: "Language",
  subLanguage: "Select App Language",
  termCondition: "Terms & Conditions",
  policy: "Privacy Policy",
  faq: "FAQ",
  support: "Contact Support",
  send: "Send",
  invite: "Invite",
  smsVerification: "SMS Verification",
  setPhone: "Set phone number",
  blockedList: "Blocked Users",
  verifyTitle: "Enter the OTP you received by SMS",
  changePhone: "Wrong phone number? ",
  change: "change",
  OTP: "OTP",
  resendCode: "Send Again",
  blockedUser: "Blocked Users",
  unBlock: "Unblock",
  selectLanguage: "Select Language",
  japanese: "Japanese",
  english: "English",
  shippingAddress: "Shipping Address",
  shippingDetails: "Shipping Details",
  gender: "Gender",
  addresses: "Addresses",
  address: "address",
  newAddress: "New Address",
  noAddress: "You have not Selected address yet!",
  addNewAddress: "Add New Address",
  addressDetail: "Address Detail",
  zipCode: "Zip Code",
  state: "State",
  country: "Country",
  day: "Day",
  year: "Year",
  month: "Month",
  city: "City",
  inviteDetail: "Enter your friends email address to invite them to LOE",
  switchDetail:
    "Professional accounts can market your products in the online shop, organize paid events, create donations, access to privileged events, and post advertisement in the app.",
  monthly: "Monthly",
  yearly: "Yearly",
  perMonth: "Per Month",
  paySubscription: "Pay for Subscription",
  pay: "Pay",
  yearlyProAccount: "Yearly pro account",
  fee: "Fee",
  totalCost: "Total Cost",
  payable: "payable",
  creditCard: "Credit Card",
  balance: "Balance",
  selectMetod: "Select The Payment Method",
  yourBalance: "Your Balance",
  titleIncreaseBalance: "Enter the amount you want to increase your balance.",
  orderDelivery: "Order Delivery",
  orderReciept: "Order Reciept",
  orderRequest: "Order Request",
  eventOnCalender: "Event On Calender",
  confirmEvent: "Confirm Event",
  createEvent: "Create Event",
  newCommunity: "New Community",
  Ads: "Ads",
  NotWithdraw: "Not Withdraw",
  DeliveryConfirmedByCustomer: "Delivery Confirmed by Customer",
  BuyTicket: "Buy Ticket",
  comment: "Comment",
  Follow: "Follow",
  joinedSuccessfuly: "Joined Successfuly",
  deleteAccount: "Delete Account",
  SureDeleteAccount: "Are you sure to delete account?",
  interests: "Interests",
  newCategory: "New Category",
  sendBill: "Send Bill",
  maxShippingDays: "Maximum Shipping Days",
  minShippingDays: "Minimum Shipping Days",

  //Payment
  payforDonation: "Pay for Donation",
  selectAmount: "Select The Payment Amount",
  amount: "Amount",
  ticketPrice: "Ticket Price",
  successfulReserve: "Successful Reserve",
  successfulPayment: "Successful Payment",
  increaseBalance: "Increase Balance",
  ProfessionalSubscriptions: "Professional Subscriptions",
  HistoryOfVariousPayments: "History of various payments",
  subIncreaseBalance: "You can increase your balance for payments in app",
  paymentsHistory: "Payments History",
  subPaymentsHistory: "History of various payments",
  boughtTickets: "Bought Tickets",
  TicketsPayments: "Tickets Payments",
  TicketsYouHavePurchased: "Tickets you have purchased",
  subBoughtTickets: "Tickets you have purchased",
  contributedDonations: "Contributed Donations",
  DonationsPayments: "Donations Payments",
  DonationsYouHaveContributed: "Donations you have contributed",
  subContributedDonations: "Donations you have contributed",
  payforTickets: "Pay for Tickets",
  ShopPayments: "Shop Payments",
  quantity: "Quantity",
  paymentId: "Payment ID",
  successful: "Successful",
  failed: "Failed",
  donation: "Donation",
  ticket: "Ticket",
  tickets: "Tickets",

  buyProduct: "Buy Product ",
  advertisement: "Advertisement",
  advertisements: "Advertisements",

  subscription: "Subscription",
  payment: "Payment",
  free: "Free",

  //Report
  reportTitle: "Why are you reporting this content?",
  spam: "It's Spam",
  nudity: "Nudity or Sexual Activity",
  hate: "Hate speech or Symbols",
  scam: "Scam or Fraud",
  something: "Something else",
  reportedAt: "Report at ",
  //Community
  loading: "Loading...",
  new: "+ New",
  newPlus: "New",
  addNewCommunity: "Add New Community",
  communityName: "Community Name",
  about: "About",
  aboutCommunity: "About Community",
  createCommunity: "Create Community",
  inviteMembers: "Invite Members",
  noOneInvited: "No One Invited",
  inviteViaEmail: "Invite via Email",
  noInvitationSent: "No Invitation sent",
  membersInvited: "Members Invited",
  invitationSent: "Invitation sent",
  emails: "Emails",
  inviteMember: "Invite",
  members: "Members",
  addPost: "Add Post in Community",
  inviteNewMembers: "Invite New Members",
  joinThisCommunity: "Join This Community",
  editCommunity: "Edit Community",
  edit: "Edit",
  selectCategory: "Select Category",
  category: "Category",
  inviteViaLink: "Invite via Link",
  communities: "Communities",

  //Profile
  followrs: "Followers",
  payments: "Payments",
  suspendUser: "Suspend User",
  deleteUser: "Delete User",

  //AddPost
  addPostTitle: "Add Post",
  addMedia: "Add Media",
  addEvent: "Add Event",
  addPlace: "Add Place",
  addSpecial: "Add Special",
  addBlog: "Add Blog",
  special: "Special",
  addLocation: "Add Location",
  writeSomething: "Write Something",
  deleteMediaTitle: "Delete Media",
  deleteMediaDescription: "Are you sure you want to delete the media?",
  deleteEventTitle: "Delete Event",
  deleteEventDescription: "Are you sure you want to delete the event?",
  deletePlaceTitle: "Delete Spot",
  deletePlaceDescription: "Are you sure you want to delete the spot?",
  deleteSpecialTitle: "Delete Special",
  deleteSpecialDescription: "Are you sure you want to delete the special?",
  deleteBlogTitle: "Delete Blog",
  deleteBlogDescription: "Are you sure you want to delete the blog?",
  delete: "Delete",
  eventTitle: "Event Title",
  placeTitle: "Place Title",
  specialTitle: "Title",
  description: "Description",
  eventMedia: "Event Media",
  spotMedia: "Spot Media",
  media: "Media",
  startingDate: "Starting Date",
  endingDate: "Ending Date",
  startingTime: "Starting Time",
  endingTime: "Ending Time",
  expireDate: "Expire Date",
  link: "Link",
  location: "Location",
  minCapacity: "Min Capatity",
  maxCapacityEvent: "Max Capatity",
  select: "Select",
  petition: "Petition",
  text: "Text",
  deletePostTitle: "Delete Content",
  deletePostDescription: "Are you sure you want to delete the content?",

  //Ads
  newAdvertisement: "New Advertisement",
  addAdvertisement: "Add Advertisement",
  adsMedia: "Ads Media",
  adsTitle: "Ads Title",
  requestedViews: "Requested Views",
  wantToDiscard: "Are you sure you want to discard the changes?",
  discard: "Discard",
  discardChanges: "Discard Changes",
  adsDetails: "Ads Details",
  advertisementInfo: "Advertisement Info",
  billRequestedAt: "Bill Requested at",
  dontSend: "Not sent by admin yet",
  payForAds: "Pay for Ads",
  userInfo: "User Info",
  orderId: "Order ID",
  notPaid: "Not Paid",
  rejectAds: "Reject Ads",
  rejectAdsDescription: "Are you sure you want to reject this ads?",
  cost: "Cost",
  sendSuccessfull: "Bill Sent Successfully",
  //admin
  oneUserReported: "user reported this content",
  severalUsersReported: " users reported this content",
  zeroUserReported: "0 user reported this content",
  reported: "Reported",
  accounts: "Accounts",
  notReviewed: "Not Reviewed",
  reviewed: "Reviewed",
  question: "Question",
  answer: "Answer",
  confirmedNewCommunity: "Confirmed New Community",
  professional: "Professional",
  until: "Until",

  //Financial and payments
  yourPrivateBalance: "Your Private Balance",
  subCreatedDonations: "Details of donations you have created",
  subCreatedTickets: " Details of the tickets you have created",
  proFeaturesPaymentHistory: "Pro Features Payment History",
  subrPoFeaturesPaymentHistory: "History of your shop, tickets and donations",
  createdTickets: "Created Tickets",
  createdDonations: "Created Donations",
  approve: "Approve",
  confirmCommunityMessage: "Do you want to confirm this community?",
  rejectCommunityMessage: "Do you want to reject this community?",

  confirmEventMessage: "Do you want to confirm this event?",
  rejectEventMessage: "Do you want to reject this event?",

  addNewSection: "New Section",
};
